/**
 * Reusable document text formatter for sharing/exporting Applications and Complaints.
 * 
 * Produces TWO formats:
 * - Plain text (for TXT download, clipboard)
 * - Formatted text with Unicode formatting (for WhatsApp, Email sharing)
 */

import { type LangCode, salutations, closings, subjectLabel, dateLabel, toLabel, formatDateByLang } from '@/data/languages';
import { fillTemplate, buildDynamicSubject } from '@/utils/templateEngine';

/**
 * Convert ASCII text to Unicode bold sans-serif characters.
 */
const toBold = (text: string): string => {
  const boldMap: Record<string, string> = {};
  for (let i = 0; i < 26; i++) {
    boldMap[String.fromCharCode(65 + i)] = String.fromCodePoint(0x1D5D4 + i);
  }
  for (let i = 0; i < 26; i++) {
    boldMap[String.fromCharCode(97 + i)] = String.fromCodePoint(0x1D5EE + i);
  }
  for (let i = 0; i < 10; i++) {
    boldMap[String.fromCharCode(48 + i)] = String.fromCodePoint(0x1D7EC + i);
  }
  return text.split('').map(c => boldMap[c] || c).join('');
};

const LINE = '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';
const THIN_LINE = '─────────────────────────────';

/**
 * Build plain text document from structured data.
 * Skips empty optional fields gracefully.
 */
export function buildDocumentText(opts: {
  title: string;
  data: Record<string, string>;
  bodyTemplate: string;
  lang: LangCode;
  showBranding?: boolean;
}): string {
  const { title, data, bodyTemplate, lang, showBranding = true } = opts;
  const today = formatDateByLang(new Date().toISOString(), lang);
  const body = fillTemplate(bodyTemplate, data, lang);
  const dynamicSubject = buildDynamicSubject(title, data);

  const lines: string[] = [];

  lines.push(data.senderName || '[Your Name]');
  if (data.senderAddress?.trim()) lines.push(data.senderAddress);
  if (data.senderPhone?.trim()) lines.push(`Phone: ${data.senderPhone}`);
  if (data.senderEmail?.trim()) lines.push(`Email: ${data.senderEmail}`);
  lines.push(`${dateLabel[lang]}: ${today}`);
  lines.push('');
  lines.push(toLabel[lang]);
  lines.push(data.recipientName || '[Recipient]');
  lines.push(data.recipientOrg || '[Organization]');
  if (data.recipientAddress?.trim()) lines.push(data.recipientAddress);
  lines.push('');
  lines.push(`${subjectLabel[lang]}: ${dynamicSubject}`);
  lines.push('');
  lines.push(salutations[lang]);
  lines.push('');
  lines.push(body);
  lines.push('');
  lines.push(closings[lang]);
  lines.push(data.senderName || '[Your Name]');
  if (data.idType?.trim() && data.idNumber?.trim()) {
    lines.push(`${data.idType}: ${data.idNumber}`);
  }
  if (data.senderPhone?.trim()) lines.push(`Contact: ${data.senderPhone}`);

  if (showBranding) {
    lines.push('');
    lines.push('— Generated by Ravomix');
  }

  return lines.join('\n');
}

/**
 * Build richly formatted document text for WhatsApp/Email sharing.
 * Skips empty optional fields gracefully.
 */
export function buildFormattedDocumentText(opts: {
  title: string;
  data: Record<string, string>;
  bodyTemplate: string;
  lang: LangCode;
  showBranding?: boolean;
}): string {
  const { title, data, bodyTemplate, lang, showBranding = true } = opts;
  const today = formatDateByLang(new Date().toISOString(), lang);
  const body = fillTemplate(bodyTemplate, data, lang);
  const dynamicSubject = buildDynamicSubject(title, data);

  const lines: string[] = [];

  // Header
  lines.push(LINE);
  lines.push(`  📄  ${toBold(title.toUpperCase())}`);
  lines.push(LINE);
  lines.push('');

  // Sender block
  lines.push(`${toBold(data.senderName || '[Your Name]')}`);
  if (data.senderAddress?.trim()) lines.push(`📍 ${data.senderAddress}`);
  if (data.senderPhone?.trim()) lines.push(`📞 ${data.senderPhone}`);
  if (data.senderEmail?.trim()) lines.push(`✉️ ${data.senderEmail}`);
  lines.push(`📅 ${dateLabel[lang]}: ${today}`);
  lines.push('');
  lines.push(THIN_LINE);
  lines.push('');

  // Recipient block
  lines.push(`${toBold(toLabel[lang])}`);
  lines.push(data.recipientName || '[Recipient]');
  lines.push(data.recipientOrg || '[Organization]');
  if (data.recipientAddress?.trim()) lines.push(`📍 ${data.recipientAddress}`);
  lines.push('');
  lines.push(THIN_LINE);
  lines.push('');

  // Subject — dynamic
  lines.push(`${toBold(subjectLabel[lang])}: ${dynamicSubject}`);
  lines.push('');

  // Salutation
  lines.push(salutations[lang]);
  lines.push('');

  // Body
  const bodyParagraphs = body.split('\n');
  for (const para of bodyParagraphs) {
    lines.push(para);
  }
  lines.push('');
  lines.push(THIN_LINE);
  lines.push('');

  // Closing
  lines.push(closings[lang]);
  lines.push('');
  lines.push(`${toBold(data.senderName || '[Your Name]')}`);
  if (data.idType?.trim() && data.idNumber?.trim()) {
    lines.push(`🪪 ${data.idType}: ${data.idNumber}`);
  }
  if (data.senderPhone?.trim()) lines.push(`📞 Contact: ${data.senderPhone}`);

  if (showBranding) {
    lines.push('');
    lines.push(THIN_LINE);
    lines.push('📎 Generated by Ravomix');
  }

  return lines.join('\n');
}
